---
kind: pipeline
name: default

steps:
- name: run-tests
  image: golang
  commands:
    - go test ./...
  when:
    event:
      - push
      - pull-request

---
kind: signature
hmac: 1984e3acf5cc7e4c5944f777126dc556ed97997a3a9ff719f6eeb42b53c5159f

...
