---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: run-tests
  image: golang
  environment:
    GOPROXY: https://proxy.golang.org

  commands:
  - go test ./...
  volumes:
  - name: go
    path: /root/.cache/go-build
  when:
    event:
    - push
    - pull-request
    - tag

- name: build
  image: golang
  environment:
    GOPROXY: https://proxy.golang.org
  commands:
  - go build -trimpath -o /tmp/build/goGoGameBot ./cmd/goGoGameBot.go
  - "echo \"goGoGameBot version $DRONE_TAG\" > /tmp/build/releaseTitle"
  volumes:
  - name: go
    path: /root/.cache/go-build
  - name: build
    path: /tmp/build
  when:
    event:
    - tag

- name: do-release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.ferricyanide.solutions
    checksum:
    - md5
    - sha256
    draft: true
    files:
    - /tmp/build/goGoGameBot
    title: /tmp/build/releaseTitle
  volumes:
  - name: go
    path: /root/.cache/go-build
  - name: build
    path: /tmp/build
  when:
    event:
    - tag

volumes:
- name: go
  temp: {}
- name: build
  temp: {}

---
kind: signature
hmac: 1b5add86757b788535f067d5dc38b74ae037bba29d3d132acfebe0e1a99b6725

...
