---
kind: pipeline
name: default

steps:
- name: run-tests
  image: golang
  commands:
    - go test ./...
  when:
    event:
      - push
      - pull-request
    branch:
      - master
      - feature/*
      - cleanup-interfaces
---
kind: signature
hmac: 768b129a682b66fce2a0195743de4629b9c20a32c95978e1fda559e2bf497ff4

...
