package mutexTypes

// Code generated by go run genMutexTypes.go DO NOT EDIT.
//go:generate go run ./generate/genMutexTypes.go

import (
	"sync"
	"time"
)

// MutexBool is a bool wrapped with a sync.RWMutex.
type MutexBool struct {
	x bool
	m sync.RWMutex
}

// Get fetches the stored value in a concurrent safe manner
func (x *MutexBool) Get() bool {
	x.m.RLock()
	defer x.m.RUnlock()
	return x.x
}

// Set sets the stored value in a concurrent safe manner
func (x *MutexBool) Set(thing bool) {
	x.m.Lock()
	x.x = thing
	x.m.Unlock()
}

// MutexInt is a int wrapped with a sync.RWMutex.
type MutexInt struct {
	x int
	m sync.RWMutex
}

// Get fetches the stored value in a concurrent safe manner
func (x *MutexInt) Get() int {
	x.m.RLock()
	defer x.m.RUnlock()
	return x.x
}

// Set sets the stored value in a concurrent safe manner
func (x *MutexInt) Set(thing int) {
	x.m.Lock()
	x.x = thing
	x.m.Unlock()
}

// MutexStringSlice is a []string wrapped with a sync.RWMutex.
type MutexStringSlice struct {
	x []string
	m sync.RWMutex
}

// Get fetches the stored value in a concurrent safe manner
func (x *MutexStringSlice) Get() []string {
	x.m.RLock()
	defer x.m.RUnlock()
	return x.x
}

// Set sets the stored value in a concurrent safe manner
func (x *MutexStringSlice) Set(thing []string) {
	x.m.Lock()
	x.x = thing
	x.m.Unlock()
}

// MutexDuration is a time.Duration wrapped with a sync.RWMutex.
type MutexDuration struct {
	x time.Duration
	m sync.RWMutex
}

// Get fetches the stored value in a concurrent safe manner
func (x *MutexDuration) Get() time.Duration {
	x.m.RLock()
	defer x.m.RUnlock()
	return x.x
}

// Set sets the stored value in a concurrent safe manner
func (x *MutexDuration) Set(thing time.Duration) {
	x.m.Lock()
	x.x = thing
	x.m.Unlock()
}

// MutexTime is a time.Time wrapped with a sync.RWMutex.
type MutexTime struct {
	x time.Time
	m sync.RWMutex
}

// Get fetches the stored value in a concurrent safe manner
func (x *MutexTime) Get() time.Time {
	x.m.RLock()
	defer x.m.RUnlock()
	return x.x
}

// Set sets the stored value in a concurrent safe manner
func (x *MutexTime) Set(thing time.Time) {
	x.m.Lock()
	x.x = thing
	x.m.Unlock()
}
