name: Lint and Test

on:
  push:
    branches:
      - "master"
      - "feature/*"

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v3
        with:
          stable: true

      - name: test
        run: go test -json ./... > test.json

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.4.0
        with:
          test-results: test.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v3
        with:
          stable: true

      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.31
          # TODOs should be warned locally, but not on here
          args: "--exclude 'LINE CONTAINS TODO/BUG/FIXME: '"
          only-new-issues: true
