name: Build and Release
on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: true

      - name: test
        run: go test -json ./... > test.json

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.1
        with:
          test-results: test.json

  build:
    name: Build GGGB and release
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Build GGGB
        run: |
          go build -trimpath -ldflags "-X git.ferricyanide.solutions/A_D/goGoGameBot/internal/version.Version=v0.5.0" -o goGoGameBot ./cmd/goGoGameBot.go
          sha256sum goGoGameBot > sha256.sum

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          body: See the CHANGELOG file for changes.
          files: |
            goGoGameBot
            sha256.sum
