name: Build and Release
on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-go@v2
        with:
          stable: true

      - name: test
        run: go test -json ./... > test.json

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.4.0
        with:
          test-results: test.json

  build:
    name: Build GGGB and release
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.0

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Build GGGB
        id: build_gggb
        run: |
          export VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=VERSION::$VERSION
          go build -trimpath -ldflags "-X awesome-dragon.science/go/goGoGameBot/internal/version.Version=$VERSION" -o goGoGameBot ./cmd/goGoGameBot.go
          sha256sum goGoGameBot > sha256.sum

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.build_gggb.outputs.VERSION }}
          body: See the CHANGELOG file for changes.
          files: |
            goGoGameBot
            sha256.sum
